const rawResult = {
  'vs-1': '1',
  'vs-2': '0',
  'vs-3': '1',
  'vs-4': '0',
  'vs-5': '1',
  'vs-6': '0',
  'vs-7': '1',
  'vs-8': '0',
  'vs-9': '0',
  'vs-10': '0',
  'vs-11': '0',
  'vs-12': '1',
  'vs-13': '0',
  'vs-14': '1',
  'vs-15': '0',
  'vs-16': '0',
  'vs-17': '0',
  'vs-18': '1',
  'vs-19': '1',
  'vs-20': '0',
  'vs-21': '0',
  'vs-22': '0',
  'vs-23': '0',
  'vs-24': '1',
  'vs-25': '0',
  'vs-26': '0',
  'vs-27': '1'
};

const formattedResult = {
  '0':
    [{ id: 'sansaStark', nameToDisplay: 'Sansa Stark', status: 'alive' },
    { id: 'branStark', nameToDisplay: 'Bran Stark', status: 'alive' },
    { id: 'jaimeLannister', nameToDisplay: 'Jaime Lannister', status: 'alive' },
    { id: 'daenerysTargaryen', nameToDisplay: 'Daenerys Targaryen', status: 'alive' },
    { id: 'yaraGreyjoy', nameToDisplay: 'Yara Greyjoy', status: 'alive' },
    { id: 'theonGreyjoy', nameToDisplay: 'Theon Greyjoy', status: 'alive' },
    { id: 'euronGreyjoy', nameToDisplay: 'Euron Greyjoy', status: 'alive' },
    { id: 'jorahMormont', nameToDisplay: 'Jorah Mormont', status: 'alive' },
    { id: 'theMountain', nameToDisplay: 'The Mountain', status: 'alive' },
    { id: 'samwellTarly', nameToDisplay: 'Samwell Tarly', status: 'alive' },
    { id: 'gilly', nameToDisplay: 'Gilly', status: 'alive' },
    { id: 'brienneOfTarth', nameToDisplay: 'Brienne of Tarth', status: 'alive' },
    { id: 'davosSeaworth', nameToDisplay: 'Davos Seaworth', status: 'alive' },
    { id: 'bronn', nameToDisplay: 'Bronn', status: 'alive' },
    { id: 'podrickPayne', nameToDisplay: 'Podrick Payne', status: 'alive' },
    { id: 'greyWorm', nameToDisplay: 'Grey Worm', status: 'alive' },
    { id: 'gendry', nameToDisplay: 'Gendry', status: 'alive' }],
  '1':
    [{ id: 'jonSnow', nameToDisplay: 'Jon Snow', status: 'alive' },
    { id: 'aryaStark', nameToDisplay: 'Arya Stark', status: 'alive' },
    { id: 'cerseiLannister', nameToDisplay: 'Cersei Lannister', status: 'alive' },
    { id: 'tyrionLannister', nameToDisplay: 'Tyrion Lannister', status: 'alive' },
    { id: 'melisandre', nameToDisplay: 'Melisandre', status: 'alive' },
    { id: 'theHound', nameToDisplay: 'The Hound', status: 'alive' },
    { id: 'samChild', nameToDisplay: 'Sam (Small Child)', status: 'alive' },
    { id: 'lordVarys', nameToDisplay: 'Lord Varys', status: 'alive' },
    { id: 'tormundGiantsbane', nameToDisplay: 'Tormund Giantsbane', status: 'alive' },
    { id: 'bericDondarrion', nameToDisplay: 'Beric Dondarrion', status: 'alive' }]
};

module.exports = { rawResult, formattedResult };
